# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(default='No venue yet', max_length=120)),
                ('phone', models.CharField(default='None', max_length=15)),
                ('details', models.TextField()),
            ],
        ),
    ]
