# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180113_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Guest Post', 'Guest Post'), ('Griots', 'Griots'), ('Class', 'Class'), ('Dictionary', 'Dictionary'), ('Biography', 'Biography'), ('Articles', 'Articles'), ('Bookshop', 'Bookshop')], default='Guest Post', max_length=50),
        ),
    ]
