# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20180113_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Guest Post'), ('Griots', 'Griots'), ('Class', 'Class'), ('Dictionary', 'Dictionary'), ('Biography', 'Biography'), ('Articles', 'Articles'), ('Bookshop', 'Bookshop')], default='1', max_length=50),
        ),
    ]
