# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20180222_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='about_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebooks',
            name='book_type',
            field=models.CharField(choices=[('ebook', 'Ebook'), ('paperback', 'Paperback')], default='ebook', max_length=120),
        ),
    ]
