# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180225_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
