# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-11 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20180225_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Griots', 'Griots'), ('Contest', 'Contest'), ('News', 'News')], default='Griots', max_length=50),
        ),
    ]
