# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20180311_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
