# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20180502_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
