# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_cart_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Contest', 'Contest'), ('News', 'News'), ('Fiction', 'Fiction'), ('Poetry', 'Poetry'), ('Articles', 'Articles'), ('Creative', 'Creative')], default='Articles', max_length=50),
        ),
    ]
