# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_ebooks_the_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooks',
            name='book_type',
        ),
    ]
