# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0027_remove_ebooks_about_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_books', to='posts.Ebooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
