# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooks',
            name='the_pdf',
        ),
        migrations.AddField(
            model_name='ebooks',
            name='ebook_file',
            field=models.FileField(null=True, upload_to='ebooks'),
        ),
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='cover',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, width_field='width_field'),
        ),
    ]
