# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-30 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20180830_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Fiction', 'Fiction'), ('Poetry', 'Poetry'), ('Articles', 'Articles'), ('Creative', 'Creative')], default='Articles', max_length=50),
        ),
    ]
