# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20180909_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
