# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-12 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_aboutus_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='text',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='text',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='text',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
