# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20180912_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
