# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0031_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommeded_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Ebooks')),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Poetry', 'Poetry'), ('Short Fiction (4500 words max)', 'Short Fiction'), ('Creative short non fiction (4500 words max)', 'Non Fiction')], default='Poetry', max_length=50)),
                ('manuscript', models.CharField(max_length=254)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
