# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 00:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='contestant',
        ),
        migrations.AddField(
            model_name='contestant',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='random_string',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contesting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='manuscript',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
