# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20180802_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='bought_book',
            field=models.BooleanField(default=False),
        ),
    ]
