# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180107_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
