# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180321_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expert_badge',
            field=models.BooleanField(default=False),
        ),
    ]
