# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 04:28
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_expert_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
